apiVersion: v1
kind: ConfigMap
metadata:
  name: mqsc-setting
  namespace: cp4i-test-1
data:
  qm.mqsc: |
    DEFINE CHANNEL(MVP.APP.CHL) CHLTYPE(SVRCONN)
    SET CHLAUTH(MVP.APP.CHL) TYPE(BLOCKUSER) USERLIST('nobody')
    SET CHLAUTH('*') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(NOACCESS)
    SET CHLAUTH(MVP.APP.CHL) TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) CHCKCLNT(REQUIRED)
    ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) ADOPTCTX(YES)
    ALTER QMGR ACCTMQI(ON) ACCTQ(ON) MONCHL(MEDIUM) MONQ(MEDIUM) STATCHL(MEDIUM) STATMQI(ON) STATQ(ON)
    REFRESH SECURITY TYPE(CONNAUTH)
    DEFINE QLOCAL(APP.EVENTS.QUEUE) MAXDEPTH(100) REPLACE
    DEFINE QLOCAL(APP.DEMO) MAXDEPTH(100) REPLACE
    DEFINE QLOCAL(APP.CRIT.QUEUE) MAXDEPTH(100) DEFPSIST(YES) REPLACE
    DEFINE QLOCAL(APP.QUEUE) STRMQOS(MUSTDUP) STREAMQ(APP.EVENTS.QUEUE) MAXDEPTH(100) REPLACE
    SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('1001') AUTHADD(CONNECT,INQ)
    SET AUTHREC PROFILE(APP.EVENTS.QUEUE) OBJTYPE(QUEUE) PRINCIPAL('1001') AUTHADD(ALLMQI)
    SET AUTHREC PROFILE(APP.CRIT.QUEUE) OBJTYPE(QUEUE) PRINCIPAL('1001') AUTHADD(ALLMQI)
    REFRESH SECURITY
